### PR TITLE
fix: Add plugin path to Importer.cs

### PR DESCRIPTION
**Pull request by liudger**
To solve importing texture from plugin if plugin is not in package folder. Not sure if this is the best way to handle the path

### CODE REVIEW

**Comment by soupday** [comment]
It's not guaranteed to the be the folders file name. Just searching all of "Assets" might be better. 

I'm currently working on a unified single package that has unity packages for each pipeline version that installs all the relevant shaders and materials into the assets folder. So I'll leave this pull request up as it has some implications for that.

**Comment by liudger** [comment]
@soupday How is the unified version going? I am really interested in this as we have now standard pipline and working on URP version. So this would help a lot. Willing to test

**Comment by liudger** [comment]
We can close this ticket I guess as using it as a package should be fine

**Comment by soupday** [comment]
> @soupday How is the unified version going? I am really interested in this as we have now standard pipline and working on URP version. So this would help a lot. Willing to test

Unified version is up for testing: https://github.com/soupday/ccic_unity_tools_all/releases if you want to try it.

**Pull request closed without merging**
